# /etc/keyd/default.conf
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)

# Remaps the escape key to capslock
# esc = capslock

# by F.C.
#
# *** Laptop Lenovo Legion Pro 5 16ADR10 ***
# Keyd configuration for Microsoft "Copilot" key remapping. Such key
# physically triggers the sequence "LeftShift + LeftMeta + F3"; the
# keyd daemon intercepts it and remaps it to "Right CTRL". Keyd needs
# "CONFIG_INPUT_UINPUT=m" in the kernel (the module is automatically
# loaded). Because such mapping happens at low level, it works with
# both X11/Wayland and any desktop environment (to verify that, run
# "libinput debug-events --show-keycodes" and press the Copilot key).
#
# NOTE: By default, keyd spawns a virtual keyboard and a virtual pointer;
# the latter is seen by KDE as external mouse; to prevent KDE Plasma from
# disabling the internal touchpad, specific rules have been added to udev
# (see /etc/udev/rules.d/99-keyd-ignore-pointer.rules) and libinput quirks
# (see /etc/libinput/local-overrides.quirks).

[main]
leftshift+leftmeta+f23=rightcontrol
