# by F.C.
#
# For ARM architecture CPU_FLAGS_ARM must be used
# (see https://wiki.gentoo.org/wiki/CPU_FLAGS_X86).
#
# See also:
# - /etc/portage/env/nosseavx.conf
# - /etc/portage/make.conf/00-cflags.conf
# - /etc/portage/binrepos.conf/gentoobinhost.conf (if binary packages are used).


# Minimal set available on the generic "x86-64" architecture (these
# flags are also used to build the Gentoo 'x86-64' binary packages).
#CPU_FLAGS_X86="mmx mmxext sse sse2"

# Minimal set available on the generic "x86-64-v3" architecture (these
# flags are also used to build the Gentoo 'x86-64-v3' binary packages).
#CPU_FLAGS_X86="avx avx2 f16c fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"

# Optimized flags for CPU AMD Ryzen 9 5900X (cerberus host). From app-portage/cpuid2cpuflags.
#CPU_FLAGS_X86="aes avx avx2 bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"

# Optimized flags for CPU AMD Ryzen 9 8940HX (sigfrido host). From app-portage/cpuid2cpuflags.
CPU_FLAGS_X86="aes avx avx2 avx512_bf16 avx512_bitalg avx512_vbmi2 avx512_vnni avx512_vpopcntdq avx512bw avx512cd avx512dq avx512f avx512ifma avx512vbmi avx512vl bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"
