# by F.C
#
# Settings for video (gpu), input and camera devices
# (see also /etc/portage/package.use/01-local-hw.use).


# GPU SECTION
# -----------
# If unset, VIDEO_CARDS defaults to 'amdgpu dummy fbdev intel nouveau radeon radeonsi vesa'.
# Flag i915 is required only for Intel GPU Gen 2 and Gen 3 (should not be used in Gen >= 4), see
# https://wiki.gentoo.org/wiki/Intel; some flags have been removed from portage (all valid video
# card flags are listed in https://packages.gentoo.org/useflags/video_cards_vesa), while other
# flags are related to very old GPU's hardware (r100, r128, r200, r300, r600, via) or ARM GPUs.
#
# NOTE: Mesa-25.2.x drops the Gallium-XA state tracker (used to accelerate X11 within the VMware
# virtualized environments, see https://www.phoronix.com/news/Mesa-Stop-Building-XA); for the time
# being, the flag 'vmware' in VIDEO_CARDS pull in "x11-drivers/xf86-video-vmware" that requires the
# (dropped) 'xa' flag in mesa, raising conflicts; so we must drop 'vmware' from VIDEO_CARDS (such
# flag is not required for the VMSVGA driver in VirtualBox, see https://bugs.gentoo.org/957955).
VIDEO_CARDS="amdgpu fbdev i965 intel nvidia qxl radeon radeonsi vesa virtualbox virgl"

# Set the AMD target architectures for HIP/ROCm (see https://wiki.gentoo.org/wiki/ROCm
# and https://llvm.org/docs/AMDGPUUsage.html). Multiple targets can be specified here
# (e.g "gfx1030 gfx1031"), but the build time of packages dependent on AMDGPU_TARGETS
# will likely increase. Therefore, it is recommended to add only the target required.
#
# Radeon 610M (iGPU, Dragon Range, RDNA 2.0, gfx1036).
# See https://www.techpowerup.com/gpu-specs/radeon-610m.c4021
AMDGPU_TARGETS="gfx1036"

# Configure CUDA capabilities for PYTORCH/CAFFE2 (for Geforce
# RTX 50XX series, see https://developer.nvidia.com/cuda/gpus).
TORCH_CUDA_ARCH_LIST=12.0


# INPUT SECTION
# -------------
# If unset, INPUT_DEVICES defaults to 'libinput' only (for a list of allowed input devices, see
# https://packages.gentoo.org/useflags/input_devices_void). Flag 'wacom' pulls in "libwacom" that
# has support for many non-Wacom graphics tablets, see https://github.com/linuxwacom/libwacom). An
# alternative driver is "OpenTabletDriver" from the guru overlay, but it conflicts with "libwacom"
# (do not install them together, see https://forums.gentoo.org/viewtopic-t-1169433-start-0.html).
# Also, proper drivers must be enabled in kernel (e.g. CONFIG_HID_UCLOGIC=m/y for Huion tablets).
#
# For KDE/PLASMA KCM configuration module we need "wacom" use flag in "kde-plasma/plasma-meta".
# Unfortunately the tablet configuration modules differ between X11 and Wayland (especially the
# button mappings), making challenging to use any graphic tablet with the same application under
# both X11 and Wayland (a possible workaround might be to remap the tablet's buttons under X11
# to match their behaviour under Wayland, but this is tablet-specific); there are also some other
# differences. Note that KDE/PLASMA 6.8 will become Wayland-exclusive, dropping support for X11.
INPUT_DEVICES="libinput wacom"


# CAMERA SECTION
# --------------
# This is used by libgphoto2. If you want to include only specific
# camera(s), set CAMERAS below ('*' means all, thas is the default).
#CAMERAS="*"
