# by F.C.

# AMDGPU and ATI RADEON modules are not meant to be
# loaded simultaneously, so when using AMDGPU, it is
# recommended to unset or blacklist the RADEON module.
# See https://wiki.gentoo.org/wiki/AMDGPU
blacklist radeon

# The watchdog (AMD: sp5100_tco, INTEL: iTCO_wdt, ACPI: wdat_wdt) can
# sometimes delay the shutdown/reboot; desktops and laptops do not need
# the watchdog, so we can disable it. We should also append 'nowatchdog'
# to the boot parameters. Additionally, disabling watchdog timers will
# increases performance and lowers power consumption.
blacklist sp5100_tco
blacklist iTCO_wdt
blacklist wdat_wdt

# Obsoleted, conflicts with CUPS USB backend.
blacklist usblp

# You probably want this to not get the
# console beep loud on every tab :)
blacklist pcspkr
