# by F.C.
#
# Build packages with GCC 14 (which must be installed). Some packages
# (with the 'cuda' USE flag enabled) fail to build with the default GCC
# because "dev-util/nvidia-cuda-toolkit-12.9.*" requires GCC < 15. THIS
# IS NO LONGER REQUIRED: "dev-util/nvidia-cuda-toolkit-13.*" is now in
# portage and supports GCC <= 16. However, I kept this for reference.
CC="x86_64-pc-linux-gnu-gcc-14"
CXX="x86_64-pc-linux-gnu-g++-14"
