# by F.C.
#
# Build packages with gcc-14 (that must be installed). Some packages
# (with the use flag 'cuda' enabled) fail to build with default gcc,
# because "dev-util/nvidia-cuda-toolkit-12.9.*" needs gcc < 15.
CC="x86_64-pc-linux-gnu-gcc-14"
CXX="x86_64-pc-linux-gnu-g++-14"
